DELETE http://localhost:3001/api/persons/62616ad1c162b619f9cb9ddd

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "ABC",
  "number": "012345 3456"
}

###

HEAD http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

// Get accurate id
GET http://localhost:3001/api/persons/625fd4e7ba76725d2a12e0b2

###

// Get wrong id, but correct format
GET http://localhost:3001/api/persons/625fd4e7ba76725d2a12e0b4

###

// Get wrong id with wrong format
GET http://localhost:3001/api/persons/lololol

### 

POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "AB",
  "number": "012345 3456"
}